const ROWS=9,COLS=7,TYPES=["𓂀","𓆣","𓋹","☀","◆","𓃭"],BONUS_TARGET=6;
let board=Array.from({length:ROWS},()=>Array(COLS).fill(null)),next=randomType(),score=0,level=1,combos=0,meter=0,busy=false,selected=3,soundOn=true;
const $=s=>document.querySelector(s),boardEl=$("#board"),buttonsEl=$("#columnButtons");
const rand=n=>Math.floor(Math.random()*n),randomType=()=>rand(Math.min(TYPES.length,4+Math.floor(level/3)));
function tone(freq=440,d=.08){if(!soundOn)return;const c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)}
function relic(type,extra=""){return type===null?"":`<span class="relic ${extra}" data-type="${type}">${TYPES[type]}</span>`}
function render(popSet=new Set()){boardEl.innerHTML="";for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const cell=document.createElement("div");cell.className="cell";cell.setAttribute("role","gridcell");const key=r+","+c;cell.innerHTML=relic(board[r][c],popSet.has(key)?"pop":"");boardEl.append(cell)}$("#nextBall").outerHTML=`<span id="nextBall" class="relic preview" data-type="${next}">${TYPES[next]}</span>`;updateHud()}
function updateHud(){$("#score").textContent=score.toLocaleString("es");$("#level").textContent=level;$("#combos").textContent=combos;$("#meter").style.width=(meter/BONUS_TARGET*100)+"%";$("#meterText").textContent=meter+" / "+BONUS_TARGET}
function lowest(col){for(let r=ROWS-1;r>=0;r--)if(board[r][col]===null)return r;return-1}
function connected(r,c,type,seen=new Set()){const key=r+","+c;if(r<0||r>=ROWS||c<0||c>=COLS||seen.has(key)||board[r][c]!==type)return seen;seen.add(key);connected(r+1,c,type,seen);connected(r-1,c,type,seen);connected(r,c+1,type,seen);connected(r,c-1,type,seen);return seen}
function matches(){const found=new Set(),seen=new Set();for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const key=r+","+c;if(board[r][c]===null||seen.has(key))continue;const group=connected(r,c,board[r][c]);group.forEach(x=>seen.add(x));if(group.size>=3)group.forEach(x=>found.add(x))}return found}
function gravity(){for(let c=0;c<COLS;c++){const vals=[];for(let r=ROWS-1;r>=0;r--)if(board[r][c]!==null)vals.push(board[r][c]);for(let r=ROWS-1;r>=0;r--)board[r][c]=vals[ROWS-1-r]??null}}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function resolve(){let chain=0;while(true){const set=matches();if(!set.size)break;chain++;render(set);tone(520+chain*90,.14);await wait(360);set.forEach(key=>{const [r,c]=key.split(",").map(Number);board[r][c]=null});score+=set.size*100*chain*level;combos++;meter=Math.min(BONUS_TARGET,meter+1);gravity();render();await wait(220)}level=1+Math.floor(score/5000);if(meter>=BONUS_TARGET)await bonusMode()}
async function drop(col,type=next,automatic=false){if(busy&&!automatic)return false;const row=lowest(col);if(row<0){if(!automatic){$("#message").textContent="Esa columna está llena. Busca otro camino.";tone(120,.18)}return false}if(!automatic)busy=true;board[row][col]=type;if(!automatic)next=randomType();render();tone(260,.08);await wait(330);await resolve();if(!automatic){busy=false;checkEnd()}return true}
async function bonusMode(){meter=0;$("#bonusChute").classList.add("active");$("#message").textContent="¡CANAL DEL DESTINO! Horus reparte 8 reliquias.";tone(720,.3);render();await wait(650);for(let i=0;i<8;i++){const available=Array.from({length:COLS},(_,c)=>c).filter(c=>lowest(c)>=0);if(!available.length)break;const col=available[rand(available.length)],type=randomType();await drop(col,type,true);await wait(160)}$("#bonusChute").classList.remove("active");score+=1000*level;render();$("#message").textContent="El Ojo se cierra. Continúa la expedición."}
function checkEnd(){if(Array.from({length:COLS},(_,c)=>lowest(c)).every(r=>r<0)){busy=true;$("#message").textContent="El templo está sellado. Toca aquí para comenzar de nuevo.";$("#message").onclick=reset}}
function choose(c){selected=c;[...buttonsEl.children].forEach((b,i)=>b.classList.toggle("active",i===c))}
function reset(){board=Array.from({length:ROWS},()=>Array(COLS).fill(null));score=0;level=1;combos=0;meter=0;next=randomType();busy=false;$("#message").onclick=null;$("#message").textContent="Elige una columna. Une 3 reliquias iguales.";render()}
for(let c=0;c<COLS;c++){const b=document.createElement("button");b.textContent="▼";b.setAttribute("aria-label","Soltar en columna "+(c+1));b.onclick=()=>{choose(c);drop(c)};buttonsEl.append(b)}
$("#dropButton").onclick=()=>drop(selected);$("#sound").onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?"♫":"×"};$("#start").onclick=()=>{$("#intro").classList.add("hidden");render()};choose(selected);render();
